name: Release Userscript

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
        
    - name: Extract version from tag
      id: get_version
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Version: $VERSION"
        
    - name: Update version in userscript
      run: |
        # Update userscript version
        sed -i "s/@version      [0-9.-]*[a-z]*/@version      ${{ steps.get_version.outputs.version }}/" script.user.js
        echo "Updated userscript version to ${{ steps.get_version.outputs.version }}"
        grep "@version" script.user.js
        
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create v${{ steps.get_version.outputs.version }} \
          --title "AO3 Vanity v${{ steps.get_version.outputs.version }}" \
          --notes "## AO3 Vanity v${{ steps.get_version.outputs.version }}

        ### Installation
        1. Install [Tampermonkey](https://www.tampermonkey.net/) browser extension
        2. Click on the userscript file below to install it
        3. Visit any [AO3 page](https://archiveofourown.org/) to see Twitter search links

        ### Changes
        See the commit history for detailed changes in this release." \
          ./script.user.js \
          ./script-info.md
